version: "3.7"
services:
    front:
        image: tombursch/kitchenowl-web:latest
        ports: 
            - "5922:80"
        restart: on-failure
        depends_on:
        - back

    back:
        image: tombursch/kitchenowl:latest
        restart: on-failure
        environment:
        - JWT_SECRET_KEY=${APP_SEED}
        - FRONT_URL=umbrelscape-kitchenowl_front_1
        volumes:
        - ${APP_DATA_DIR}/data/back:/data