version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umbrelscape-flaresolverr_server_1
      APP_PORT: 8191
      PROXY_AUTH_ADD: "false"

  server:
    image: flaresolverr/flaresolverr:v3.0.2
    environment:
      - PUID=1000
      - PGID=1000
    restart: on-failure